version: "3.8"

# demo with itegrated influx
services:
  spot-hinta-influxdb:
    image: vonlatvala/spot-hinta-influxdb
    environment:
      - TZ=Europe/Helsinki
      - EXEC_INTERVAL_MINUTES=30
      - INFLUX_DATABASE=spot_price
      - INFLUX_PASSWORD=secret
      - INFLUX_PORT=8086
      - INFLUX_PROTO=http
      - INFLUX_USERNAME=system
      - UPSTREAM_API_FQDN=api.spot-hinta.fi
      - UPSTREAM_API_PROTO=https
      - INFLUX_HOST=influxdb
      - INCLUDE_TOMORROW=true
    restart: unless-stopped
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=spot_price
      - INFLUXDB_ADMIN_USER=system
      - INFLUXDB_ADMIN_PASSWORD=secret
    volumes:
      - influxdb-storage:/var/lib/influxdb

volumes:
  influxdb-storage:
